import {
  FileText,
  Combine,
  Scissors,
  Minimize2,
  FileOutput,
  Shield,
  Lock,
  Unlock,
  ImageDown,
  Droplet,
  RotateCw,
  FileImage,
  FileSpreadsheet,
  Presentation,
  FileDigit,
  Crop,
  Trash2,
  PenTool,
  FileInput,
  FileCode,
  Eraser,
  Sparkles,
  Scan,
  GitCompare,
  Layers,
  FileSearch,
  MessageSquare,
  Brain,
  type LucideIcon,
  FileType,
  Type,
  Code,
  MonitorUp,
  Wand2,
  Settings2,
  Link,
  Link2,
  Paperclip,
  Gauge,
  CheckCircle2,
  FileX,
  Download,
  ImageIcon,
  BookOpen,
  Bookmark,
  Eye,
  Volume2,
  Clipboard,
  Unlink,
  Printer,
  List,
  Hash,
  Grid3X3,
  Package,
  RefreshCw,
  Layers2,
  Frame,
  Move,
  Binary,
  Scale,
  Maximize2,
  Info,
  Languages,
  MessageCircle,
  Lightbulb,
  ListOrdered,
  Sparkle,
  Wrench,
  History,
  Star,
  Search,
  ChevronDown,
  Keyboard,
  Share2,
  BarChart3,
  Upload,
  DownloadCloud,
  Clock,
  Crown,
  Key,
  FileBarChart,
  Zap,
  Image,
  Palette,
  Grid2X2,
  Stamp,
  SpellCheck2,
  type LucideIcon,
} from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  gradient: string;
  acceptTypes: string;
  maxFiles: number;
  popular?: boolean;
  endpoint: string;
  outputFormat: string;
  difficulty?: "easy" | "medium" | "advanced";
  category?: string;
  hints?: string[];
}

export interface ToolCategory {
  name: string;
  description: string;
  icon: LucideIcon;
  gradient: string;
  tools: Tool[];
}

export const toolCategories: ToolCategory[] = [
  {
    name: "PDF Tools",
    description: "Essential PDF manipulation tools",
    icon: FileText,
    gradient: "from-violet-500 to-purple-600",
    tools: [
      {
        id: "merge",
        name: "Merge PDF",
        description: "Combine multiple PDF files into one document",
        icon: Combine,
        gradient: "from-orange-400 to-pink-500",
        acceptTypes: ".pdf",
        maxFiles: 999, // Unlimited - no file limit for merge
        popular: true,
        endpoint: "/api/pdf/merge",
        outputFormat: "PDF",
      },
      {
        id: "split",
        name: "Split PDF",
        description: "Extract pages or split PDF into multiple files",
        icon: Scissors,
        gradient: "from-red-400 to-rose-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/split",
        outputFormat: "PDF",
      },
      {
        id: "compress",
        name: "Compress PDF",
        description: "Reduce PDF file size while maintaining quality",
        icon: Minimize2,
        gradient: "from-green-400 to-emerald-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/compress",
        outputFormat: "PDF",
      },
      {
        id: "pdf-to-word",
        name: "PDF to Word",
        description: "Convert PDF documents to editable Word files",
        icon: FileOutput,
        gradient: "from-blue-400 to-indigo-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/to-word",
        outputFormat: "DOCX",
      },
      {
        id: "pdf-to-excel",
        name: "PDF to Excel",
        description: "Extract tables from PDF to Excel spreadsheets",
        icon: FileSpreadsheet,
        gradient: "from-green-500 to-teal-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/to-excel",
        outputFormat: "XLSX",
      },
      {
        id: "pdf-to-ppt",
        name: "PDF to PowerPoint",
        description: "Convert PDF pages to PowerPoint presentation",
        icon: Presentation,
        gradient: "from-orange-500 to-red-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/to-ppt",
        outputFormat: "PPTX",
      },
      {
        id: "pdf-to-image",
        name: "PDF to Image",
        description: "Convert PDF pages to high-quality images",
        icon: ImageDown,
        gradient: "from-purple-400 to-violet-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/to-image",
        outputFormat: "PNG/JPG",
      },
    ],
  },
  {
    name: "Convert to PDF",
    description: "Convert various file formats to PDF",
    icon: FileInput,
    gradient: "from-blue-500 to-cyan-600",
    tools: [
      {
        id: "word-to-pdf",
        name: "Word to PDF",
        description: "Convert Word documents to PDF format",
        icon: FileInput,
        gradient: "from-blue-500 to-indigo-600",
        acceptTypes: ".doc,.docx",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/from-word",
        outputFormat: "PDF",
      },
      {
        id: "excel-to-pdf",
        name: "Excel to PDF",
        description: "Convert Excel spreadsheets to PDF documents",
        icon: FileSpreadsheet,
        gradient: "from-green-500 to-emerald-600",
        acceptTypes: ".xls,.xlsx",
        maxFiles: 1,
        endpoint: "/api/pdf/from-excel",
        outputFormat: "PDF",
      },
      {
        id: "ppt-to-pdf",
        name: "PPT to PDF",
        description: "Convert PowerPoint presentations to PDF",
        icon: Presentation,
        gradient: "from-orange-500 to-red-600",
        acceptTypes: ".ppt,.pptx",
        maxFiles: 1,
        endpoint: "/api/pdf/from-ppt",
        outputFormat: "PDF",
      },
      {
        id: "image-to-pdf",
        name: "Image to PDF",
        description: "Convert images to PDF document",
        icon: FileImage,
        gradient: "from-pink-500 to-rose-600",
        acceptTypes: ".jpg,.jpeg,.png,.gif,.bmp,.webp",
        maxFiles: 50,
        popular: true,
        endpoint: "/api/pdf/from-image",
        outputFormat: "PDF",
      },
      {
        id: "html-to-pdf",
        name: "HTML to PDF",
        description: "Convert HTML pages to PDF documents",
        icon: FileCode,
        gradient: "from-cyan-500 to-blue-600",
        acceptTypes: ".html,.htm",
        maxFiles: 1,
        endpoint: "/api/pdf/from-html",
        outputFormat: "PDF",
      },
    ],
  },
  {
    name: "PDF Editing",
    description: "Edit and modify PDF documents",
    icon: PenTool,
    gradient: "from-pink-500 to-rose-600",
    tools: [
      {
        id: "watermark",
        name: "Add Watermark",
        description: "Add text or image watermark to PDF",
        icon: Droplet,
        gradient: "from-cyan-400 to-blue-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/watermark",
        outputFormat: "PDF",
      },
      {
        id: "page-numbers",
        name: "Add Page Numbers",
        description: "Add page numbers to PDF document",
        icon: FileDigit,
        gradient: "from-violet-400 to-purple-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/page-numbers",
        outputFormat: "PDF",
      },
      {
        id: "rotate",
        name: "Rotate PDF",
        description: "Rotate PDF pages to any angle",
        icon: RotateCw,
        gradient: "from-amber-400 to-orange-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/rotate",
        outputFormat: "PDF",
      },
      {
        id: "crop",
        name: "Crop PDF",
        description: "Crop PDF pages to custom size",
        icon: Crop,
        gradient: "from-lime-400 to-green-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/crop",
        outputFormat: "PDF",
      },
      {
        id: "delete-pages",
        name: "Delete Pages",
        description: "Remove unwanted pages from PDF",
        icon: Trash2,
        gradient: "from-red-400 to-rose-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/delete-pages",
        outputFormat: "PDF",
      },
      {
        id: "organize",
        name: "Organize PDF",
        description: "Reorder, rotate, and delete pages with drag & drop",
        icon: Layers,
        gradient: "from-indigo-400 to-purple-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/organize",
        outputFormat: "PDF",
      },
    ],
  },
  {
    name: "PDF Security",
    description: "Protect and secure your PDF documents",
    icon: Shield,
    gradient: "from-amber-500 to-orange-600",
    tools: [
      {
        id: "protect",
        name: "Protect PDF",
        description: "Add password protection to PDF",
        icon: Lock,
        gradient: "from-red-500 to-rose-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/protect",
        outputFormat: "PDF",
      },
      {
        id: "unlock",
        name: "Unlock PDF",
        description: "Remove password from protected PDF",
        icon: Unlock,
        gradient: "from-green-500 to-emerald-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/unlock",
        outputFormat: "PDF",
      },
      {
        id: "sign",
        name: "Sign PDF",
        description: "Add digital signature to PDF",
        icon: PenTool,
        gradient: "from-blue-500 to-indigo-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/sign",
        outputFormat: "PDF",
      },
      {
        id: "redact",
        name: "Redact PDF",
        description: "Permanently remove sensitive information",
        icon: Eraser,
        gradient: "from-gray-500 to-slate-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/redact",
        outputFormat: "PDF",
      },
    ],
  },
  {
    name: "AI-Powered Tools",
    description: "Smart PDF tools powered by artificial intelligence",
    icon: Brain,
    gradient: "from-purple-500 to-indigo-600",
    tools: [
      {
        id: "ocr",
        name: "OCR PDF",
        description: "Extract text from scanned PDFs using AI",
        icon: Scan,
        gradient: "from-teal-400 to-cyan-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/ocr",
        outputFormat: "DOCX/TXT",
      },
      {
        id: "compare",
        name: "Compare PDFs",
        description: "Compare two PDFs and highlight differences",
        icon: GitCompare,
        gradient: "from-orange-400 to-amber-500",
        acceptTypes: ".pdf",
        maxFiles: 2,
        endpoint: "/api/pdf/compare",
        outputFormat: "PDF Report",
      },
      {
        id: "summarize",
        name: "Summarize PDF",
        description: "Generate AI summary of PDF content",
        icon: FileSearch,
        gradient: "from-violet-500 to-purple-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/summarize",
        outputFormat: "TXT/PDF",
      },
      {
        id: "chat",
        name: "Chat with PDF",
        description: "Ask questions about your PDF documents",
        icon: MessageSquare,
        gradient: "from-pink-500 to-rose-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/chat",
        outputFormat: "Interactive",
      },
    ],
  },
  {
    name: "Extract & Convert",
    description: "Extract content and convert to various formats",
    icon: FileType,
    gradient: "from-teal-500 to-cyan-600",
    tools: [
      {
        id: "pdf-to-markdown",
        name: "PDF to Markdown",
        description: "Convert PDF text to Markdown format",
        icon: FileType,
        gradient: "from-blue-500 to-cyan-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/markdown",
        outputFormat: "MD",
        difficulty: "easy",
        hints: ["Best for text-based PDFs", "Preserves formatting"],
      },
      {
        id: "pdf-to-text",
        name: "PDF to Text",
        description: "Extract plain text from PDF",
        icon: Type,
        gradient: "from-gray-500 to-slate-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/text",
        outputFormat: "TXT",
        difficulty: "easy",
      },
      {
        id: "pdf-to-html",
        name: "PDF to HTML",
        description: "Convert PDF to HTML format",
        icon: Code,
        gradient: "from-orange-500 to-amber-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/html",
        outputFormat: "HTML",
        difficulty: "medium",
      },
      {
        id: "pdf-to-xps",
        name: "PDF to XPS",
        description: "Convert PDF to XPS document format",
        icon: MonitorUp,
        gradient: "from-blue-600 to-indigo-700",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/xps",
        outputFormat: "XPS",
        difficulty: "medium",
      },
      {
        id: "pdf-to-epub",
        name: "PDF to EPUB",
        description: "Convert PDF to EPUB ebook format",
        icon: BookOpen,
        gradient: "from-purple-500 to-pink-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/epub",
        outputFormat: "EPUB",
        difficulty: "medium",
      },
      {
        id: "pdf-to-pdfa",
        name: "PDF to PDF/A",
        description: "Convert to archival PDF/A format",
        icon: FileBarChart,
        gradient: "from-emerald-500 to-teal-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/pdfa",
        outputFormat: "PDF/A",
        difficulty: "advanced",
      },
      {
        id: "extract-images",
        name: "Extract Images",
        description: "Extract all images from PDF",
        icon: ImageIcon,
        gradient: "from-yellow-500 to-orange-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/extract-images",
        outputFormat: "ZIP (Images)",
        difficulty: "easy",
      },
      {
        id: "extract-pages",
        name: "Extract Pages",
        description: "Extract specific pages as new PDF",
        icon: Download,
        gradient: "from-cyan-500 to-blue-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/extract-pages",
        outputFormat: "PDF",
        difficulty: "easy",
      },
      {
        id: "extract-attachments",
        name: "Extract Attachments",
        description: "Extract file attachments from PDF",
        icon: Paperclip,
        gradient: "from-rose-500 to-pink-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/extract-attachments",
        outputFormat: "ZIP (Files)",
        difficulty: "medium",
      },
      {
        id: "extract-links",
        name: "Extract Links",
        description: "Extract hyperlinks from PDF",
        icon: Link,
        gradient: "from-sky-500 to-blue-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/extract-links",
        outputFormat: "JSON/TXT",
        difficulty: "easy",
      },
    ],
  },
  {
    name: "Image & Color Tools",
    description: "Convert and manipulate PDF images and colors",
    icon: Palette,
    gradient: "from-pink-500 to-rose-600",
    tools: [
      {
        id: "pdf-grayscale",
        name: "PDF to Grayscale",
        description: "Convert PDF to grayscale",
        icon: Palette,
        gradient: "from-gray-400 to-slate-500",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/grayscale",
        outputFormat: "PDF",
        difficulty: "easy",
      },
      {
        id: "pdf-cmyk-rgb",
        name: "CMYK to RGB",
        description: "Convert CMYK colorspace to RGB",
        icon: Palette,
        gradient: "from-cyan-500 to-teal-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/cmyk-to-rgb",
        outputFormat: "PDF",
        difficulty: "advanced",
      },
      {
        id: "image-quality",
        name: "Change Image Quality",
        description: "Reduce image quality in PDF",
        icon: Gauge,
        gradient: "from-amber-500 to-orange-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/image-quality",
        outputFormat: "PDF",
        difficulty: "medium",
      },
      {
        id: "optimize-web",
        name: "Optimize for Web",
        description: "Linearize PDF for fast web viewing",
        icon: Gauge,
        gradient: "from-green-500 to-emerald-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/optimize",
        outputFormat: "PDF",
        difficulty: "medium",
      },
    ],
  },
  {
    name: "Repair & Optimize",
    description: "Fix and optimize PDF files",
    icon: Wrench,
    gradient: "from-amber-500 to-orange-600",
    tools: [
      {
        id: "repair",
        name: "Repair PDF",
        description: "Repair corrupted PDF files",
        icon: Wrench,
        gradient: "from-red-500 to-orange-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/repair",
        outputFormat: "PDF",
        difficulty: "advanced",
      },
      {
        id: "validate",
        name: "Validate PDF",
        description: "Validate PDF/A compliance",
        icon: CheckCircle2,
        gradient: "from-green-500 to-emerald-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/validate",
        outputFormat: "Report",
        difficulty: "advanced",
      },
      {
        id: "flatten",
        name: "Flatten PDF",
        description: "Flatten annotations and form fields",
        icon: Layers2,
        gradient: "from-violet-500 to-purple-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/flatten",
        outputFormat: "PDF",
        difficulty: "medium",
      },
      {
        id: "embed-fonts",
        name: "Embed Fonts",
        description: "Embed missing fonts in PDF",
        icon: Type,
        gradient: "from-blue-500 to-indigo-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/embed-fonts",
        outputFormat: "PDF",
        difficulty: "advanced",
      },
    ],
  },
  {
    name: "Annotations & Links",
    description: "Add and manage PDF annotations and links",
    icon: Bookmark,
    gradient: "from-indigo-500 to-purple-600",
    tools: [
      {
        id: "add-page-border",
        name: "Add Page Border",
        description: "Add border/frame to PDF pages",
        icon: Frame,
        gradient: "from-pink-500 to-rose-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/add-border",
        outputFormat: "PDF",
        difficulty: "easy",
      },
      {
        id: "auto-bookmarks",
        name: "Auto Bookmarks",
        description: "Add bookmarks automatically from headings",
        icon: Bookmark,
        gradient: "from-teal-500 to-cyan-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/auto-bookmarks",
        outputFormat: "PDF",
        difficulty: "medium",
      },
      {
        id: "add-links",
        name: "Add Links",
        description: "Add hyperlinks to PDF pages",
        icon: Link2,
        gradient: "from-sky-500 to-blue-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/add-links",
        outputFormat: "PDF",
        difficulty: "medium",
      },
    ],
  },
  {
    name: "Metadata & Security",
    description: "Manage PDF metadata and permissions",
    icon: Settings2,
    gradient: "from-slate-500 to-gray-600",
    tools: [
      {
        id: "change-metadata",
        name: "Change Metadata",
        description: "Edit title, author, subject, keywords",
        icon: Info,
        gradient: "from-violet-500 to-purple-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/metadata",
        outputFormat: "PDF",
        difficulty: "easy",
      },
      {
        id: "remove-metadata",
        name: "Remove Metadata",
        description: "Strip all metadata from PDF",
        icon: Eraser,
        gradient: "from-gray-500 to-slate-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/remove-metadata",
        outputFormat: "PDF",
        difficulty: "easy",
      },
      {
        id: "set-permissions",
        name: "Set Permissions",
        description: "Set print/copy/edit permissions",
        icon: Lock,
        gradient: "from-red-500 to-rose-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/set-permissions",
        outputFormat: "PDF",
        difficulty: "advanced",
      },
      {
        id: "unlock-brute",
        name: "Unlock (Try Passwords)",
        description: "Try common passwords to unlock PDF",
        icon: Unlink,
        gradient: "from-amber-500 to-orange-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/unlock-brute",
        outputFormat: "PDF",
        difficulty: "advanced",
        hints: ["Educational use only", "May take time"],
      },
    ],
  },
  {
    name: "Layout & Imposition",
    description: "Change page layout and imposition",
    icon: Grid2X2,
    gradient: "from-cyan-500 to-blue-600",
    tools: [
      {
        id: "impose",
        name: "Impose (N-up)",
        description: "Put multiple pages per sheet",
        icon: Grid2X2,
        gradient: "from-purple-500 to-pink-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/impose",
        outputFormat: "PDF",
        difficulty: "medium",
      },
      {
        id: "stamp-multiple",
        name: "Batch Stamp",
        description: "Stamp multiple PDFs in batch",
        icon: Stamp,
        gradient: "from-orange-500 to-red-600",
        acceptTypes: ".pdf",
        maxFiles: 20,
        endpoint: "/api/pdf/stamp-multiple",
        outputFormat: "ZIP (PDFs)",
        difficulty: "medium",
      },
    ],
  },
  {
    name: "AI Tools",
    description: "AI-powered PDF features",
    icon: Sparkle,
    gradient: "from-violet-500 to-indigo-600",
    tools: [
      {
        id: "tts",
        name: "Text to Speech",
        description: "Read PDF aloud with AI voice",
        icon: Volume2,
        gradient: "from-blue-500 to-cyan-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        popular: true,
        endpoint: "/api/pdf/tts",
        outputFormat: "Audio",
        difficulty: "easy",
      },
      {
        id: "translate",
        name: "Translate PDF",
        description: "Translate PDF content to different languages",
        icon: Languages,
        gradient: "from-green-500 to-teal-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/translate",
        outputFormat: "PDF/TXT",
        difficulty: "medium",
      },
      {
        id: "grammar-fix",
        name: "Fix Grammar",
        description: "Fix grammar and spelling in PDF text",
        icon: SpellCheck2,
        gradient: "from-yellow-500 to-amber-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/grammar-fix",
        outputFormat: "PDF/DOCX",
        difficulty: "medium",
      },
      {
        id: "key-points",
        name: "Extract Key Points",
        description: "Extract key points and highlights",
        icon: Lightbulb,
        gradient: "from-amber-500 to-orange-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/key-points",
        outputFormat: "TXT",
        difficulty: "medium",
      },
      {
        id: "generate-toc",
        name: "Generate TOC",
        description: "Generate table of contents",
        icon: ListOrdered,
        gradient: "from-indigo-500 to-purple-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/generate-toc",
        outputFormat: "MD/JSON",
        difficulty: "medium",
      },
      {
        id: "smart-extract",
        name: "Smart Extract",
        description: "AI-powered intelligent content extraction",
        icon: Sparkle,
        gradient: "from-violet-500 to-purple-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/smart-extract",
        outputFormat: "JSON/TXT",
        difficulty: "advanced",
      },
      {
        id: "summarize-sections",
        name: "Summarize Sections",
        description: "Summarize specific page ranges",
        icon: FileSearch,
        gradient: "from-teal-500 to-cyan-600",
        acceptTypes: ".pdf",
        maxFiles: 1,
        endpoint: "/api/pdf/summarize-sections",
        outputFormat: "TXT",
        difficulty: "medium",
      },
    ],
  },
];

// Get all tools flattened
export const getAllTools = (): Tool[] => {
  return toolCategories.flatMap((category) => category.tools);
};

// Get popular tools
export const getPopularTools = (): Tool[] => {
  return getAllTools().filter((tool) => tool.popular);
};

// Get tool by ID
export const getToolById = (id: string): Tool | undefined => {
  return getAllTools().find((tool) => tool.id === id);
};

// Get category for a tool
export const getCategoryForTool = (toolId: string): ToolCategory | undefined => {
  return toolCategories.find((category) =>
    category.tools.some((tool) => tool.id === toolId)
  );
};

// Get tools by difficulty
export const getToolsByDifficulty = (difficulty: "easy" | "medium" | "advanced"): Tool[] => {
  return getAllTools().filter((tool) => tool.difficulty === difficulty);
};

// Search tools by name or description
export const searchTools = (query: string): Tool[] => {
  const lowerQuery = query.toLowerCase();
  return getAllTools().filter(
    (tool) =>
      tool.name.toLowerCase().includes(lowerQuery) ||
      tool.description.toLowerCase().includes(lowerQuery) ||
      tool.id.toLowerCase().includes(lowerQuery)
  );
};

// Get all tool IDs
export const getAllToolIds = (): string[] => {
  return getAllTools().map((tool) => tool.id);
};

// Get tool categories as flat list for sidebar
export interface CategoryItem {
  name: string;
  icon: LucideIcon;
  gradient: string;
  tools: Tool[];
  toolCount: number;
}

export const getCategoryItems = (): CategoryItem[] => {
  return toolCategories.map((cat) => ({
    name: cat.name,
    icon: cat.icon,
    gradient: cat.gradient,
    tools: cat.tools,
    toolCount: cat.tools.length,
  }));
};
